name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: |
          echo "Running tests with shorter timeout and verbose output..."
          go test -buildvcs=false -timeout=2m -v -race ./tests/compression/...
          go test -buildvcs=false -timeout=2m -v -race ./tests/crypto/...
          go test -buildvcs=false -timeout=2m -v -race ./tests/data/...
          go test -buildvcs=false -timeout=2m -v -race ./tests/utils/...
          go test -buildvcs=false -timeout=2m -v -race ./tests/encoding/...
          echo "All test packages completed successfully"